# Generated by Django 2.1 on 2020-11-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='number_in_stick',
            new_name='number_in_stock',
        ),
    ]
